################################################################################
###                     Dependency configuration                             ###
################################################################################

################################################################################
###                      Custom directives                                   ###
################################################################################

################################################################################
###                       Logging configuration                              ###
################################################################################
# logging.level.org.springframework.web: DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet: DEBUG

# Springfox
logging.level.springfox.documentation: DEBUG

# This application
logging.level.net.michalfoksa.demos.workshop.workstation.http.rest.intercept: DEBUG
