################################################################################
###                     Dependency configuration                             ###
################################################################################
spring:
  application:
    name: workstation

# Display application name in Actuator's info endpoint 
info.app.name: ${spring.application.name}

management:
  # To change which endpoints are exposed, use 
  # management.endpoints.web.exposure.include and  
  # management.endpoints.web.exposure.exclude properties.
  endpoints:
    web:
      exposure:
        # Expose all actuator endpoints
        include: '*'

# API documentation in JSON format. Default value is /v2/api-docs
springfox.documentation.swagger.v2.path: /api-docs

################################################################################
###                      Custom directives                                   ###
################################################################################
service:
  discovery:
    client:
      # Protocol used to call downstream services.
      # It is also used to discover TCP port
      defaultprototol: http

################################################################################
###                       Logging configuration                              ###
################################################################################
logging.level: INFO
logging.level.org.springframework: DEBUG
logging.level.org.apache: WARN
logging.level.org.apache.tomcat: INFO
logging.level.org.hibernate: INFO
logging.level.org.thymeleaf: INFO
logging.level.net.michalfoksa: DEBUG
logging.level.net.michalfoksa.demos.workshop.workstation.http.rest.intercept: INFO
