# Log levels
# logging.level.org.springframework.web: DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet: DEBUG

# Springfox
logging.level.springfox.documentation: DEBUG

# Current application
logging.level.net.michalfoksa.demos.workshop.workstation.http.rest.intercept: DEBUG
