openapi: 3.0.0

################################################################################
#                              API Information                                 #
################################################################################
info:
  version: v1
  title: Simple task API
  description: API for managing user tasks
servers:
  - url: http://localhost/
################################################################################
#                                           Paths                              #
################################################################################
paths:
  /workorders:
    post:
      description: Create a work order
      tags:
        - workOrders
      operationId: createWorkOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/WorkOrder"
        description: Work order for a workstation
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CreateWorkOrderResponse"

################################################################################
#                                 Components                                   #
################################################################################
components:
  schemas:
    Workstation:
      description: Workstation
      required:
        - name
        - parameters
      properties:
        name:
          type: string
          description: Name of the workstation
          example: paintshop
        url:
          type: string
          description: Optional URL of the workstation. Is is appended with `/works`. When present it is used to contact
            the workstation instead of other resolver/discovery mechanism. Url parameter is usefull in local development.
          example: http://paintshop:8080
        parameters:
          type: object
          additionalProperties:
            type: string
          description: Free named parameters. They do not have any pupose, just to pass
            some data through assebly line workstations.
          example:
            engine: V8
            transmission: automatic
            bodyType: sedan
    WorkOrder:
      description: Work order for a workstation.
      required:
        - workstationName
        - followingStations
        - parameters
      properties:
        workstationName:
          type: string
          description: Name of the workstation which is supposed to execute the work.
          example: bodyshop
        parameters:
          type: object
          additionalProperties:
            type: string
          description: Free named parameters. Their only pupose is to to pass
            some data through assebly line workstations.
          example:
            engine: V8
            transmission: automatic
            bodyType: sedan
        followingStations:
          type: array
          items:
            $ref: "#/components/schemas/Workstation"
          description: List of Workstation to be called in sequence.
    MessageContext:
      description: Describes how a request or response was created.
      properties:
        correlationId:
          type: string
          description: Client generated ID to correlate all service requests in one
            business operation (transaction).
    CreateWorkOrderResponse:
      properties:
        body:
          $ref: "#/components/schemas/Workstation"
        messageContext:
          $ref: "#/components/schemas/MessageContext"
        runtimeContext:
          type: object
          additionalProperties:
            type: object
          description: Describes runtime environment of a pod or container executing the
            request.
